// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sayit.proto

package sayit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_sayit_c782cbd88c676026, []int{0}
}
func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (dst *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(dst, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Speech struct {
	Audio                []byte   `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Speech) Reset()         { *m = Speech{} }
func (m *Speech) String() string { return proto.CompactTextString(m) }
func (*Speech) ProtoMessage()    {}
func (*Speech) Descriptor() ([]byte, []int) {
	return fileDescriptor_sayit_c782cbd88c676026, []int{1}
}
func (m *Speech) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Speech.Unmarshal(m, b)
}
func (m *Speech) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Speech.Marshal(b, m, deterministic)
}
func (dst *Speech) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Speech.Merge(dst, src)
}
func (m *Speech) XXX_Size() int {
	return xxx_messageInfo_Speech.Size(m)
}
func (m *Speech) XXX_DiscardUnknown() {
	xxx_messageInfo_Speech.DiscardUnknown(m)
}

var xxx_messageInfo_Speech proto.InternalMessageInfo

func (m *Speech) GetAudio() []byte {
	if m != nil {
		return m.Audio
	}
	return nil
}

func init() {
	proto.RegisterType((*Text)(nil), "sayit.Text")
	proto.RegisterType((*Speech)(nil), "sayit.Speech")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TextToSpeechClient is the client API for TextToSpeech service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TextToSpeechClient interface {
	Say(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Speech, error)
}

type textToSpeechClient struct {
	cc *grpc.ClientConn
}

func NewTextToSpeechClient(cc *grpc.ClientConn) TextToSpeechClient {
	return &textToSpeechClient{cc}
}

func (c *textToSpeechClient) Say(ctx context.Context, in *Text, opts ...grpc.CallOption) (*Speech, error) {
	out := new(Speech)
	err := c.cc.Invoke(ctx, "/sayit.TextToSpeech/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextToSpeechServer is the server API for TextToSpeech service.
type TextToSpeechServer interface {
	Say(context.Context, *Text) (*Speech, error)
}

func RegisterTextToSpeechServer(s *grpc.Server, srv TextToSpeechServer) {
	s.RegisterService(&_TextToSpeech_serviceDesc, srv)
}

func _TextToSpeech_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToSpeechServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sayit.TextToSpeech/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToSpeechServer).Say(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

var _TextToSpeech_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sayit.TextToSpeech",
	HandlerType: (*TextToSpeechServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _TextToSpeech_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sayit.proto",
}

func init() { proto.RegisterFile("sayit.proto", fileDescriptor_sayit_c782cbd88c676026) }

var fileDescriptor_sayit_c782cbd88c676026 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4e, 0xac, 0xcc,
	0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xa4, 0xb8, 0x58, 0x42,
	0x52, 0x2b, 0x4a, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0x6c, 0x25, 0x39, 0x2e, 0xb6, 0xe0, 0x82, 0xd4, 0xd4, 0xe4, 0x0c, 0x21, 0x11,
	0x2e, 0xd6, 0xc4, 0xd2, 0x94, 0xcc, 0x7c, 0xb0, 0x34, 0x4f, 0x10, 0x84, 0x63, 0x64, 0xcc, 0xc5,
	0x03, 0xd2, 0x1b, 0x92, 0x0f, 0x55, 0xa5, 0xcc, 0xc5, 0x1c, 0x9c, 0x58, 0x29, 0xc4, 0xad, 0x07,
	0xb1, 0x07, 0x24, 0x27, 0xc5, 0x0b, 0xe5, 0x40, 0x94, 0x28, 0x31, 0x24, 0xb1, 0x81, 0xad, 0x37,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xb5, 0xa4, 0x69, 0x8d, 0x00, 0x00, 0x00,
}
